"""
Pytest configuration for integration tests.

This file sets up a real PostgreSQL database in a Docker container that all integration tests can use.
"""
import pytest
import psycopg2
from testcontainers.postgres import PostgresContainer
from utils.logger import get_logger

logger = get_logger(__name__)

@pytest.fixture(scope="session")
def postgres_container():
    """
    Start a PostgreSQL container for the entire test session.

    Scope="session" means:
    - Container starts once before ALL tests
    - All tests share the same container
    - Container stops after all tests complete

    This is fast and eficient
    """
    logger.info("Starting PostgreSQL test container...")

    with PostgresContainer("postgres:15-alpine") as postgres:
        logger.info(f"PostgreSQL container started on port {postgres.get_exposed_port(5432)}")
        yield postgres

    logger.info("PostgreSQL container stopped")

@pytest.fixture(scope="session")
def test_database_url(postgres_container):
    """
    Get the connection URL for the test database.

    This URL is automatically generated by testcontainers and points to the Docker container.
    """
    url = postgres_container.get_connection_url()
    return url.replace("postgresql+psycopg2://", "postgresql://")

@pytest.fixture(scope="session")
def database_schema(test_database_url):
    """
    Create the database schema once for all tests.

    This creates all tables we need for testing.
    """
    logger.info("Setting up database schema...")

    conn = psycopg2.connect(test_database_url)
    conn.autocommit = True
    cur = conn.cursor()

    # Create tables matching production schema exactly
    # Enable UUID extension
    cur.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    
    cur.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name VARCHAR(255),
            email VARCHAR(255) UNIQUE NOT NULL,
            password_hash VARCHAR(255) NOT NULL,
            email_verified BOOLEAN DEFAULT false,
            is_active BOOLEAN DEFAULT true,
            last_login_at TIMESTAMP,
            created_at TIMESTAMP DEFAULT now(),
            updated_at TIMESTAMP DEFAULT now()
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS products (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            description TEXT,
            image_url TEXT,
            target_price NUMERIC(12,2),
            currency VARCHAR(3) DEFAULT 'USD',
            notification_enabled BOOLEAN DEFAULT true,
            is_active BOOLEAN DEFAULT true,
            created_at TIMESTAMP DEFAULT now(),
            updated_at TIMESTAMP DEFAULT now()
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS product_links (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
            url TEXT UNIQUE NOT NULL,
            store VARCHAR(100) NOT NULL,
            product_identifier VARCHAR(255),
            last_price NUMERIC(12,2),
            lowest_price_seen NUMERIC(12,2),
            highest_price_seen NUMERIC(12,2),
            last_checked_at TIMESTAMP,
            scrape_error_count INTEGER DEFAULT 0,
            is_active BOOLEAN DEFAULT true,
            created_at TIMESTAMP DEFAULT now(),
            updated_at TIMESTAMP DEFAULT now()
        )
    """)
    
    cur.execute("""
        CREATE TABLE IF NOT EXISTS price_history (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            product_link_id UUID NOT NULL REFERENCES product_links(id) ON DELETE CASCADE,
            price NUMERIC(12,2) NOT NULL,
            original_price NUMERIC(12,2),
            discount_percentage NUMERIC(5,2),
            currency VARCHAR(3) DEFAULT 'USD',
            was_available BOOLEAN DEFAULT true,
            scrape_source VARCHAR(50),
            response_time_ms INTEGER,
            checked_at TIMESTAMP DEFAULT now()
        )
    """)

    conn.commit()
    cur.close()
    conn.close()

    logger.info("Database schema created successfully")
    yield

    logger.info("Cleaning up database schema...")

@pytest.fixture(autouse=True)
def clean_database(test_database_url, database_schema):
    """
    Clean all tables before EACH test.

    autouse=True means this runs automatically before every test.
    This ensures each test starts with a clean slate!
    """
    # Run before each test
    yield

    # Run after each test - clean up data
    conn = psycopg2.connect(test_database_url)
    conn.autocommit = True
    cur = conn.cursor()

    # Delete in reverse order of foreign key dependencies
    cur.execute("TRUNCATE TABLE price_history CASCADE")
    cur.execute("TRUNCATE TABLE product_links CASCADE")
    cur.execute("TRUNCATE TABLE products CASCADE")
    cur.execute("TRUNCATE TABLE users CASCADE")

    cur.close()
    conn.close()

@pytest.fixture
def sample_user(test_database_url):
    """
    Create a sample user for tests that need one.

    Usage in tests:
        def test_something(sample_user):
            user_id = sample_user['id']
            # ... your test code
    """
    conn = psycopg2.connect(test_database_url)
    conn.autocommit = True
    cur = conn.cursor()

    cur.execute("""
        INSERT INTO users (name, email, password_hash, email_verified, is_active)
        VALUES (%s, %s, %s, %s, %s)
        RETURNING id, email, name
    """, ('Test User', 'test@example.com', 'hashed_password_123', True, True))
    user = cur.fetchone()

    cur.close()
    conn.close()

    return {
        'id': user[0],
        'email': user[1],
        'name': user[2]
    }

@pytest.fixture
def sample_product(test_database_url, sample_user):
    """
    Create a sample product for tests.

    Automatically creates a user first (depends on sample_user fixture).
    """
    conn = psycopg2.connect(test_database_url)
    conn.autocommit = True
    cur = conn.cursor()

    cur.execute("""
        INSERT INTO products (
            user_id,
            name,
            description,
            target_price,
            currency,
            notification_enabled,
            is_active
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        RETURNING id, name, user_id, target_price
    """, (
        sample_user['id'],
        'Test Product',
        'A test product for integration tests',
        99.99,
        'USD',
        True,
        True
    ))
    product = cur.fetchone()

    cur.close()
    conn.close()

    return {
        'id': product[0],
        'name': product[1],
        'user_id': product[2],
        'target_price': product[3]
    }

@pytest.fixture
def sample_product_link(test_database_url, sample_product):
    """
    Create a sample product link for tests.

    This is particularly useful for scraper tests!
    """
    conn = psycopg2.connect(test_database_url)
    conn.autocommit = True
    cur = conn.cursor()

    cur.execute("""
        INSERT INTO product_links (
            product_id,
            url,
            store,
            product_identifier,
            is_active,
            scraper_error_count
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        RETURNING id, url, store, product_id
    """, (
        sample_product['id'],
        'https://www.amazon.com/dp/B08N5WRWNW',
        'amazon',
        'B08N5WRWNW',
        True,
        0
    ))
    link = cur.fetchone()

    cur.close()
    conn.close()

    return {
        'id': link[0],
        'url': link[1],
        'store': link[2],
        'product_id': link[3]
    }