name: Deploy Price Tracker Scraper

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Cache pip dependencies
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip            
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Run tests
              run: |
                python -m pytest tests/ -v
    
    deploy:
        needs: test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Install AWS SAM CLI
              run: |
                pip install awscli
                pip install aws-sam-cli

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
            
            - name: Build SAM application
              run: |
                cd infrastructure
                sam build
            
            - name: Deploy to AWS
              working-directory: infrastructure
              run: |
                sam deploy \
                    --stack-name price-tracker-scraper \
                    --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-qy1wi0obg6b5 \
                    --s3-prefix price-tracker-scraper \
                    --region us-east-1 \
                    --capabilities CAPABILITY_IAM \
                    --no-confirm-changeset \
                    --parameter-overrides DatabaseUrl="${{ secrets.DATABASE_URL }}" LogLevel=INFO